---
- hosts: all_horizon 
  connection: local
  gather_facts: false
  vars_files:
    - /git/vars/UDF/horizon.yml
    - /git/vars/UDF/windows.yml
  roles:
    - { role: roles/date-time}
    - { role: roles/Horizon-Roles/remove_horizon_prep}

- hosts: bigip
  connection: local
  gather_facts: false
  vars_files:
    - /git/vars/UDF/bigip.yml
    - /git/vars/horizon_iapp_ltm.yml
  roles:
    - { role: roles/date-time}
    - { role: roles/F5-Roles/f5-prep-lab}
    - { role: roles/F5-Roles/delete-irule}