---
# tasks file for Create-VM

 - name: Find Horizon Agent Install File
   ansible.windows.win_find:
     paths: c:\tools\
     patterns: 'VMware-Horizon-Agent*.exe'
   register: ag_install

 - debug:
     var: ag_install.files[0].path

 - name: Install Horizon Agent
   ansible.windows.win_package:
    path: "{{ ag_install.files[0].path }}"  
    arguments: /s /v"/qb VDM_VC_MANAGED_AGENT=0 VDM_SERVER_NAME={{ horizon_primary }} VDM_SERVER_USERNAME={{ ansible_win_domain }} VDM_SERVER_PASSWORD={{ ansible_password }} ADDLOCAL=ALL"     expected_return_code: [0, 1641]
   become: true
   become_method: runas
   become_flags: logon_type=new_credentials logon_flags=netcredentials_only
   vars:
     ansible_become_user: "{{ansible_user}}"
     ansible_become_pass: "{{ansible_password}}"
     ansible_winrm_kerberos_delegation: True
