---
#  - debug:
#      var: nsxt_segment_exists

  - name: create Segment
    nsxt_policy_segment:
      hostname: "{{ nsx_hostname }}"
      username: "{{ nsx_username }}"
      password: "{{ nsx_password }}"
      validate_certs: "{{ nsx_validate_certs }}"
      display_name: "{{ nsx_display_name }}"
      state: present
      transport_zone_display_name: "{{ nsx_transport_zone_display_name }}"
      admin_state: "{{ nsx_admin_state }}"
      connectivity_path: "{{ nsx_connectivity_path }}"
      subnets: "{{ nsx_subnets }}"
      tags: "{{ nsx_tags }}"
    when: nsxt_segment_exists|bool == false
