---
- hosts: localhost
  connection: local
  gather_facts: true
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"
    - nsxt_segment_exist: false
  vars_files:
    - ../vars/nsx.yml
  roles:
    - { role: roles/NSXT-Roles/check_manager_status, when: is_nsx_environment|bool}
    - { role: roles/NSXT-Roles/list_logical_switches, when: is_nsx_environment|bool}
    - { role: roles/NSXT-Roles/create_nsx_segment, when: is_nsx_environment|bool}
    - { role: roles/NSXT-Roles/create_nsx_segment_pause, when: is_nsx_environment|bool}

# Build F5 VMs
- hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - ../vars/vsphere.yml
    - ../vars/NSX/f5_ova.yml
  roles:
    - roles/vSphere-Roles/create_resource_pool
    - roles/vSphere-Roles/deploy_ova

#- hosts: localhost
#  connection: local
#  gather_facts: false
#  vars_files:
#    - ../vars/f5_vars_build_f5.yml
#  roles:
#    - roles/F5-Roles/reset_passwords
#    - roles/F5-Roles/configure_f5
#    - roles/F5-Roles/configure_dns
#    - roles/F5-Roles/configure_ntp
#    - roles/F5-Roles/configure_self
#    - roles/F5-Roles/save_config
#    - roles/F5-Roles/get_bigip_version
