---

- hosts: localhost
  connection: local
  tasks:

    - name: Find Installation File Names
      ansible.builtin.find:
        paths: /git/files/horizon_8x
        recurse: yes
      register: files
      delegate_to: localhost

    - debug:
        var: item.path
      with_items: files

- hosts: connection_servers
  connection: local
  gather_facts: false
  vars_files:
    - /git/vars/UDF/horizon.yml
    - /git/vars/UDF/windows.yml
  roles:
    - { role: roles/date-time}
    - { role: roles/Horizon-Roles/copy_files}

- hosts: agents
  connection: local
  gather_facts: false
  vars_files:
    - /git/vars/UDF/horizon.yml
    - /git/vars/UDF/windows.yml
  roles:
    - { role: roles/Horizon-Roles/copy_files}
    - { role: roles/date-time}
