---
- hosts: all
  gather_facts: false
  vars_files:
    - /git/vars/UDF/horizon.yml
    - /git/vars/UDF/windows.yml
  tasks:

    - name: Test connectivity to Windows hosts
      win_ping:
      when: inventory_hostname != "big-ip"

    - name: Test ALL Servers Ping to F5
      win_ping: 
        hostname: "10.1.1.4" 
