---
- hosts: connection_servers
  connection: local
  gather_facts: false
  vars_files:
    - /git/vars/UDF/horizon.yml
    - /git/vars/UDF/windows.yml
  roles:
    - { role: roles/date-time}
    - { role: roles/Horizon-Roles/remove_horizon_prep}

- hosts: agents
  connection: local
  gather_facts: false
  vars_files:
    - /git/vars/UDF/horizon.yml
    - /git/vars/UDF/windows.yml
  roles:
    - { role: roles/Horizon-Roles/remove_horizon_prep}
    - { role: roles/date-time}
