---
- hosts: bigip
  connection: local
  gather_facts: false
  vars_files:
    - /git/vars/UDF/bigip.yml
  roles:
    - { role: roles/date-time}
#    - { role: roles/F5-Roles/test_bip}
    - { role: roles/F5-Roles/license_bigip}
    - { role: roles/F5-Roles/deploy-horizon-iapp}
