---
- hosts: connection_servers
  gather_facts: false
  vars_files:
    - /git/vars/UDF/horizon.yml
    - /git/vars/UDF/windows.yml
  vars:
    array_list: []
  roles:
    - { role: roles/date-time}
    - { role: roles/Horizon-Roles/find_files}
    - { role: roles/Horizon-Roles/copy_files}
    - { role: roles/Horizon-Roles/install_horizon}

- hosts: agents
  connection: local
  gather_facts: false
  vars_files:
    - /git/vars/UDF/horizon.yml
    - /git/vars/UDF/windows.yml
  vars:
    array_list: []
  roles:
    - { role: roles/Horizon-Roles/find_files}
    - { role: roles/Horizon-Roles/copy_files}
    - { role: roles/Horizon-Roles/agent_add_rd_users}
    - { role: roles/Horizon-Roles/install_horizon}
    - { role: roles/date-time}

- hosts: connection_servers
  gather_facts: false
  vars_files:
    - /git/vars/UDF/horizon.yml
    - /git/vars/UDF/windows.yml
  vars:
    array_list: []
  roles:
    - { role: roles/date-time}
    - { role: roles/Horizon-Roles/copy_locked_properties}

- hosts: broker-cs1
  connection: local
  gather_facts: false
  vars_files:
    - /git/vars/UDF/horizon.yml
    - /git/vars/UDF/restapi.yml
  roles:
    - { role: roles/date-time}
    - { role: roles/Horizon-Roles/rest_api/login}
    - { role: roles/Horizon-Roles/rest_api/license}
    - { role: roles/Horizon-Roles/rest_api/get_group_id}
    - { role: roles/Horizon-Roles/rest_api/get_rds_server_ids}
    - { role: roles/Horizon-Roles/rest_api/create_farm}
    - { role: roles/Horizon-Roles/rest_api/get_farm_info}
    - { role: roles/Horizon-Roles/rest_api/add_rds_server_to_farm}
    - { role: roles/Horizon-Roles/rest_api/create_rds_pool}
    # - { role: roles/Horizon-Roles/rest_api/create_apps}
    # - { role: roles/Horizon-Roles/rest_api/get_app_info}
    - { role: roles/Horizon-Roles/rest_api/get_pool_info}
    - { role: roles/Horizon-Roles/rest_api/set_entitlement}
    - { role: roles/date-time}

- hosts: bigip
  connection: local
  gather_facts: false
  vars_files:
    - /git/vars/UDF/bigip.yml
    - /git/vars/horizon_iapp_ltm.yml
  roles:
    - { role: roles/date-time}
    - { role: roles/F5-Roles/license-bigip}
    - { role: roles/F5-Roles/create-irule}
    - { role: roles/F5-Roles/deploy-horizon-iapp}
