---
- hosts: all
  connection: local
  gather_facts: false
  vars_files:
    - /git/vars/UDF/horizon.yml
    - /git/vars/UDF/windows.yml
  tasks:

    - name: Test connectivity to Windows hosts
      win_ping:
      when: inventory_hostname != "big-ip"