---
- hosts: connection_servers
  gather_facts: false
  vars_files:
    - /git/vars/UDF/horizon.yml
    - /git/vars/UDF/windows.yml
  vars:
    array_list: []
  roles:
    - { role: roles/date-time}
    - { role: roles/Horizon-Roles/copy_locked_properties}

