---
  - name: Get Farm Info
    ansible.builtin.uri:
      url: "https://{{ ansible_host }}/rest/inventory/v1/application-pools"
      method: GET
      headers:
        Authorization: "Bearer {{ login_info.json.access_token }}"
        Content-Type: application/json
      status_code: 201, 200
      timeout: 300
      body_format: json
      validate_certs: false
    delegate_to: localhost
    register: get_app_info
    # no_log: true

  - name: debug
    ansible.builtin.debug:
      var: get_app_info
