---
  - name: Get-VM-Facts
    vmware_guest_info:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      validate_certs: no
      name: "{{vm_hostname}}{{item}}"
      schema: "vsphere"
      properties: ["guest.ipAddress"]
    delegate_to: localhost
    with_sequence: "start=1 count={{vm_count}} format=%.3d"
    register: info

  - name: Add VMs to dynamic_hosts Group
    add_host:
      hostname="{{vm_hostname}}{{item}}"
      ansible_host="{{info.results[item |int -1].instance.guest.ipAddress}}"
      groups=dynamic_hosts
    with_sequence: "start=1 count={{vm_count}} format=%.3d"

#  - debug:
#      msg: "{{item}}"
#    with_inventory_hostnames:
#      - dynamic_hosts

