---
  - name: GET License Horizon 
    ansible.builtin.uri:
      url: "https://{{ ansible_host }}/rest/config/v1/licenses/"
      method: GET
      headers:
        Authorization: "Bearer {{ login_info.json.access_token }}"
        Content-Type: application/json
      status_code: 204, 201, 200
      timeout: 300
      body_format: json
      validate_certs: false
    delegate_to: localhost
    register: license_info

  - name: debug
    ansible.builtin.debug:
      var: license_info

  # - name: Set License Horizon Mode
  #   ansible.builtin.uri:
  #     url: "https://{{ ansible_host }}/rest/config/v1/licenses/action/set-mode"
  #     method: POST
  #     body: 
  #       license_mode: "PERPETUAL_ONLY"
  #     headers:
  #       Authorization: "Bearer {{ login_info.json.access_token }}"
  #       Content-Type: application/json
  #     status_code: 204, 201, 200
  #     timeout: 300
  #     body_format: json
  #     validate_certs: false
  #   delegate_to: localhost
  #   register: license_info_set
  #   # no_log: true


  - name: License Horizon
    ansible.builtin.uri:
      url: "https://{{ ansible_host }}/rest/config/v2/licenses"
      method: POST
      body: 
        license_key: "{{ horizon_license }}"
      headers:
        Authorization: "Bearer {{ login_info.json.access_token }}"
        Content-Type: application/json
      status_code: 204, 201, 200
      timeout: 300
      body_format: json
      validate_certs: false
    delegate_to: localhost
    register: license_info
    # no_log: true

  - name: Horizon License Activate
    ansible.builtin.uri:
      url: "https://{{ ansible_host }}/rest/config/v1/licenses/action/validate"
      method: POST
      body: 
        license_key: "M148L-XXXXX-XXXXX-XXXXX-CDFHM"
        license_mode: "DEFAULT"
        expires: 0
      headers:
        Authorization: "Bearer {{ login_info.json.access_token }}"
        Content-Type: application/json
      status_code: 204, 201, 200
      timeout: 300
      body_format: json
      validate_certs: false
    delegate_to: localhost
    register: license_info_set
    # no_log: true

  # - name: debug
  #   ansible.builtin.debug:
  #     var: login_info

  # - name: debug
  #   ansible.builtin.debug:
  #     var: license_info
