---
  - name: Login to Horizon API
    ansible.builtin.uri:
      url: "https://{{ ansible_host }}/rest/login"
      method: POST
      body: '{"domain": "F5DEMOS", "password": ["{{ ansible_password }}"], "username": "horizon_admin"}'
      status_code: 200
      timeout: 300
      body_format: json
      validate_certs: false
    delegate_to: localhost
    register: login_info
    # no_log: true

  - name: debug
    ansible.builtin.debug:
      var: login_info

