---
# tasks file for Create-VM

 - name: Remove Horizon 7.13 Agent
   ansible.windows.win_package:
     product_id: '{6657B013-D47B-4901-9E6E-E192808FDCAB}'
     state: absent
   become: true
   become_method: runas
   become_flags: logon_type=new_credentials logon_flags=netcredentials_only
   vars:
     ansible_become_user: "{{ansible_user}}"
     ansible_become_pass: "{{ansible_password}}"
     ansible_winrm_kerberos_delegation: True
   when: horizon_version == "7x"






