---
  - name: Add RDS Server Farm
    ansible.builtin.uri:
      url: "https://{{ ansible_host }}/rest/inventory/v1/farms/{{get_farm_info.json[0].id}}/action/add-rds-servers"
      method: POST
      body: '[ "{{ physical_machine_id_info.json[0].id }}" ]'
      headers:
        Authorization: "Bearer {{ login_info.json.access_token }}"
        Content-Type: application/json
      status_code: 201, 200
      timeout: 300
      body_format: json
      validate_certs: false
    delegate_to: localhost
    register: rds_farm_info
    # no_log: true
    ignore_errors: true

  - name: debug
    ansible.builtin.debug:
      var: rds_farm_info
