---

  - name: Copy Locked.Properties file to folder
    win_copy: 
      src: "{{ lookup('template', 'locked.properites') }}"
      dest: "c:\Program Files\VMware\VMware View\Server\sslgateway\conf"
    become: true
    become_method: runas
    become_flags: logon_type=new_credentials logon_flags=netcredentials_only
    vars:
      ansible_become_user: "{{ansible_user}}"
      ansible_become_pass: "{{ansible_password}}"
      ansible_winrm_kerberos_delegation: True
