---
  - name: Create vlan portgroup {{dvs_pg_scheme}}000x
    vmware_dvs_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ vcenter_validate_certs }}"
      portgroup_name: "{{ dvs_pg_scheme }}000{{ item }}"
      switch_name: "{{ dvs_switch_name }}"
      vlan_id: "{{ item }}"
      num_ports: 250
      portgroup_type: earlyBinding
      state: present
    delegate_to: localhost
    with_sequence: start="{{ vlan_info.vlan_id_start }}" end="{{ vlan_info.vlan_id_end }}"
    when: (item |int < 10)

  - name: Create vlan portgroup {{dvs_pg_scheme}}00xx
    vmware_dvs_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ vcenter_validate_certs }}"
      portgroup_name: "{{ dvs_pg_scheme }}00{{ item }}"
      switch_name: "{{ dvs_switch_name }}"
      vlan_id: "{{ item }}"
      num_ports: 250
      portgroup_type: earlyBinding
      state: present
    delegate_to: localhost
    with_sequence: start="{{ vlan_info.vlan_id_start }}" end="{{ vlan_info.vlan_id_end }}"
    when: (item |int < 100)

  - name: Create vlan portgroup {{dvs_pg_scheme}}0xxx
    vmware_dvs_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ vcenter_validate_certs }}"
      portgroup_name: "{{ dvs_pg_scheme }}0{{ item }}"
      switch_name: "{{ dvs_switch_name }}"
      vlan_id: "{{ item }}"
      num_ports: 250
      portgroup_type: earlyBinding
      state: present
    delegate_to: localhost
    with_sequence: start="{{ vlan_info.vlan_id_start }}" end="{{ vlan_info.vlan_id_end }}"
    when: (item |int < 1000)

  - name: Create vlan portgroup {{dvs_pg_scheme}}xxxx
    vmware_dvs_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ vcenter_validate_certs }}"
      portgroup_name: "{{ dvs_pg_scheme }}{{ item }}"
      switch_name: "{{ dvs_switch_name }}"
      vlan_id: "{{ item }}"
      num_ports: 250
      portgroup_type: earlyBinding
      state: present
    delegate_to: localhost
    with_sequence: start="{{ vlan_info.vlan_id_start }}" end="{{ vlan_info.vlan_id_end }}"
    when: (item |int >= 1000)

