---

  - pause:
      minutes: 1

  - name: Delete Segment
    nsxt_policy_segment:
      hostname: "{{ nsx_hostname }}"
      username: "{{ nsx_username }}"
      password: "{{ nsx_password }}"
      validate_certs: "{{ nsx_validate_certs }}"
      display_name: "{{ nsx_display_name }}"
      state: absent

