---
# tasks file for Create-VM

 - name: Remove Horizon 8 Sub_Component
   ansible.windows.win_package:
     product_id: '{8F5617C6-F5A2-4CEE-8021-B27963AB8643}'
     state: absent
   become: true
   become_method: runas
   become_flags: logon_type=new_credentials logon_flags=netcredentials_only
   vars:
     ansible_become_user: "{{ ansible_user }}"
     ansible_become_pass: "{{ ansible_password }}"
     ansible_winrm_kerberos_delegation: True
   when: horizon_version == "8x"

 - name: Remove Horizon 8 Main Installer
   ansible.windows.win_package:
     product_id: '{5BC9F942-690D-4F7F-A121-F3A7A9E6EF7E}'
     state: absent
   become: true
   become_method: runas
   become_flags: logon_type=new_credentials logon_flags=netcredentials_only
   vars:
     ansible_become_user: "{{ ansible_user }}"
     ansible_become_pass: "{{ ansible_password }}"
     ansible_winrm_kerberos_delegation: True
   when: horizon_version == "8x"

 - name: Remove ADAM and Database
   ansible.windows.win_package:
     product_id: '{5BC9F942-690D-4F7F-A121-F3A7A9E6EF7E}'
     state: absent
   become: true
   become_method: runas
   become_flags: logon_type=new_credentials logon_flags=netcredentials_only
   vars:
     ansible_become_user: "{{ ansible_user }}"
     ansible_become_pass: "{{ ansible_password }}"
     ansible_winrm_kerberos_delegation: True
   when: horizon_version == "8x"