---
- hosts: localhost
  connection: local
  gather_facts: true
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"
  vars_files:
    - ../vars/nsx.yml
  roles:
    - roles/NSXT-Roles/check_manager_status
#    - roles/NSXT-Roles/create_nsx_segment
    - roles/NSXT-Roles/delete_nsx_segment
