---

 - name: Install RDS Server
   ansible.windows.win_feature:
     name: RDS-RD-Server
     state: present
   register: install_rds
   retries: 10
   delay: 5
   until: install_rds is not failed

##Set-RDLicenseConfiguration -LicenseServer server1 -Mode PerUser 
 - name: Agent Reboot
   ansible.windows.win_reboot:
     post_reboot_delay: 60
   when: install_rds.changed

 - name: Find Horizon Agent Install File
   ansible.windows.win_find:
     paths: c:\tools\
     patterns: 'Omnissa-Horizon-Agent*.exe'
   register: ag_install

 - debug:
     var: ag_install.files[0].path

 - name: Install Horizon Agent
   ansible.windows.win_package:
    path: "{{ ag_install.files[0].path }}"  
    arguments: /s /v"/qb VDM_VC_MANAGED_AGENT=0 VDM_SERVER_NAME={{ horizon_primary }} VDM_SERVER_USERNAME={{ ansible_win_domain }} VDM_SERVER_PASSWORD={{ ansible_password }} ADDLOCAL=ALL REBOOT=Reallysuppress"
    expected_return_code: [0, 1641, 3010]
   become: true
   become_method: runas
   become_flags: logon_type=new_credentials logon_flags=netcredentials_only
   vars:
     ansible_become_user: "{{ansible_user}}"
     ansible_become_pass: "{{ansible_password}}"
     ansible_winrm_kerberos_delegation: True

 - name: Agent Reboot
   ansible.windows.win_reboot:
     post_reboot_delay: 60
