---
# tasks file for Create-VM

 - name: Find Connection Server Install File
   ansible.windows.win_find:
     paths: c:\tools\
     patterns: 'VMware-Horizon-Connection*.exe'
   register: cs_install
   register: state
  #  until: state.rc == 0
  #  retries: 5
  #  delay: 60

 - debug:
     var: state

 - pause:
     seconds: 20

 - debug:
     var: cs_install.files[0].path

 - name: Re-Install Horizon Connection Servers
   ansible.windows.win_package:
     path: "{{ cs_install.files[0].path }}" 
     arguments: /s /v"/qn VDM_SERVER_INSTANCE_TYPE=1"
   become: true
   become_method: runas
   become_flags: logon_type=new_credentials logon_flags=netcredentials_only
   vars:
     ansible_become_user: "{{ansible_user}}"
     ansible_become_pass: "{{ansible_password}}"
     ansible_winrm_kerberos_delegation: True
   until: state.rc == 0
   retries: 5
   delay: 60