---
 - name: Install Horizon Connection Server
   include: install_cs.yml
   when: "'cs' in inventory_hostname|lower"

 - name: Install Horizon Agent
   include: install_agent.yml
   when: "'rds' in inventory_hostname|lower"