---
# tasks file for Create-VM

 - name: Install Horizon Connection Server Primary
   ansible.windows.win_package:
     path: C:\tools\VMware-HorizonCS.exe  
     arguments: /s /v"/qn VDM_SERVER_INSTANCE_TYPE=1 VDM_INITIAL_ADMIN_SID=S-1-5-32-544 VDM_SERVER_RECOVERY_PWD="VMware123!" VDM_SERVER_RECOVERY_PWD_REMINDER=""VM123Bang"""
   become: true
   become_method: runas
   become_flags: logon_type=new_credentials logon_flags=netcredentials_only
   vars:
     ansible_become_user: "{{ansible_user}}"
     ansible_become_pass: "{{ansible_password}}"
     ansible_winrm_kerberos_delegation: True
   when: "'001' in inventory_hostname"
 
 - name: Install Horizon Connection Server Secondary
   ansible.windows.win_package:
     path: C:\tools\VMware-HorizonCS.exe  
     arguments: /s /v"/qn VDM_SERVER_INSTANCE_TYPE=2 ADAM_PRIMARY_NAME=LAB-HZNCS-001.dsc-services.local VDM_INITIAL_ADMIN_SID=S-1-5-32-544" 
   become: true
   become_method: runas
   become_flags: logon_type=new_credentials logon_flags=netcredentials_only
   vars:
     ansible_become_user: "{{ansible_user}}"
     ansible_become_pass: "{{ansible_password}}"
     ansible_winrm_kerberos_delegation: True
   when: "'002' in inventory_hostname"

 - name: Install RDS Server
   ansible.windows.win_feature:
     name: RDS-RD-Server
     state: present
   when: "'003' in inventory_hostname"

#Set-RDLicenseConfiguration -LicenseServer server1 -Mode PerUser 
 - name: Agent Reboot
   ansible.windows.win_reboot:
   when: "'003' in inventory_hostname"

 - name: Install Horizon Agent
   ansible.windows.win_package:
    path: C:\tools\VMware-HorizonAG.exe  
    arguments: /s /v"/qn VDM_VC_MANAGED_AGENT=0 VDM_SERVER_NAME=Lab-HZNCS-001.dsc-services.local VDM_SERVER_USERNAME={{ansible_user}} VDM_SERVER_PASSWORD={{ansible_password}} ADDLOCAL=ALL"
    expected_return_code: [0, 1641]
   become: true
   become_method: runas
   become_flags: logon_type=new_credentials logon_flags=netcredentials_only
   vars:
     ansible_become_user: "{{ansible_user}}"
     ansible_become_pass: "{{ansible_password}}"
     ansible_winrm_kerberos_delegation: True
   when: "'003' in inventory_hostname"

# - name: Add a PowerShell module
#   community.windows.win_psmodule:
#     name: PowershellGet
#     state: present
#   when: "'001' in inventory_hostname"  

# - name: Add a PowerShell module
#   community.windows.win_psmodule:
#     name: Vmware.PowerCLI
#     state: present
#   when: "'001' in inventory_hostname"  
#Import-Module -Name VMware.VimAutomation.HorizonView 
   
