---
  - name: Create Directory
    win_file:
      path: c:\tools
      state: directory

  - name: Copy VMware Horizon files from "{{horizon_files}})
    win_copy: 
      src: "{{horizon_files}}" 
      dest: c:\tools\
    become: true
    become_method: runas
    become_flags: logon_type=new_credentials logon_flags=netcredentials_only
    vars:
      ansible_become_user: "{{ansible_user}}"
      ansible_become_pass: "{{ansible_password}}"
      ansible_winrm_kerberos_delegation: True
